### ISSUE TITLE
Adding donejs-mocha fails unless you clear node_modules folder

### ISSUE THREAD

**Issue by phillipskevin** [donejs/donejs-mocha#4]
When adding donejs-mocha, this error is thrown: 

```
steal.js:6369 TypeError: Error loading "mocha@2.4.5#mocha" at http://localhost:8080/node_modules/steal-mocha/node_modules/mocha/mocha.js(…) "TypeError: Error loading "mocha@2.4.5#mocha" at http://localhost:8080/node_modules/steal-mocha/node_modules/mocha/mocha.js
Error loading "mocha@2.4.5#mocha" from "test" at http://localhost:8080/test.js
AMD module mocha@2.4.5#mocha did not define
    at Loader.loader.instantiate (http://localhost:8080/node_modules/steal/steal.js:4405:17)
    at Loader.loader.instantiate (http://localhost:8080/node_modules/steal/steal.js:4726:32)
```

This can be fixed by removing the node_modules folder and running `npm install`.

**Comment by phillipskevin** [comment]
This is caused by https://github.com/stealjs/steal/issues/694.

**Comment by phillipskevin** [comment]
Closed by https://github.com/stealjs/steal/pull/695.
